[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://api.savtas-cookbook.com"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200