/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [],
  theme: {
    extend: {
      colors: {
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
        },
        red: {
          100: 'var(--red-100)',
          200: 'var(--red-200)',
          300: 'var(--red-300)',
          400: 'var(--red-400)',
          500: 'var(--red-500)',
        },
        blue: {
          100: 'var(--blue-100)',
          200: 'var(--blue-200)',
          300: 'var(--blue-300)',
          400: 'var(--blue-400)',
          500: 'var(--blue-500)',
        },
        green: {
          100: 'var(--green-100)',
          200: 'var(--green-200)',
          300: 'var(--green-300)',
          400: 'var(--green-400)',
          500: 'var(--green-500)',
        },
        orange: {
          100: 'var(--orange-100)',
          200: 'var(--orange-200)',
          300: 'var(--orange-300)',
          400: 'var(--orange-400)',
          500: 'var(--orange-500)',
        },
        yellow: {
          100: 'var(--yellow-100)',
          200: 'var(--yellow-200)',
          300: 'var(--yellow-300)',
          400: 'var(--yellow-400)',
          500: 'var(--yellow-500)',
        },
        purple: {
          100: 'var(--purple-100)',
          200: 'var(--purple-200)',
          300: 'var(--purple-300)',
          400: 'var(--purple-400)',
          500: 'var(--purple-500)',
        },
        // primary: {
        //   orange: 'var(--primary-orange)',
        //   brown: 'var(--primary-brown)',
        //   pink: 'var(--primary-pink)',
        //   yellow: 'var(--primary-yellow)',
        //   blue: 'var(--primary-blue)',
        // },
        // secondary: {
        //   orange: 'var(--secondary-orange)',
        //   brown: 'var(--secondary-brown)',
        //   pink: 'var(--secondary-pink)',
        //   yellow: 'var(--secondary-yellow)',
        //   blue: 'var(--secondary-blue)',
        // },
        // accent: {
        //   blue: 'var(--accent-blue)',
        //   red: 'var(--accent-red)',
        //   green: 'var(--accent-green)',
        //   orange: 'var(--accent-orange)',
        //   pink: 'var(--accent-pink)',
        //   purple: 'var(--accent-purple)',
        // },
        // bright: {
        //   blue: 'var(--bright-blue)',
        //   red: 'var(--bright-red)',
        //   green: 'var(--bright-green)',
        //   orange: 'var(--bright-orange)',
        //   pink: 'var(--bright-pink)',
        //   purple: 'var(--bright-purple)',
        // },
        // medium: {
        //   blue: 'var(--medium-blue)',
        //   red: 'var(--medium-red)',
        //   green: 'var(--medium-green)',
        //   orange: 'var(--medium-orange)',
        //   pink: 'var(--medium-pink)',
        //   purple: 'var(--medium-purple)',
        // },
        // light: {
        //   blue: 'var(--light-blue)',
        //   red: 'var(--light-red)',
        //   green: 'var(--light-green)',
        //   orange: 'var(--light-orange)',
        //   pink: 'var(--light-pink)',
        //   purple: 'var(--light-purple)',
        // },
      },
    },
  },
  plugins: [],
};
